# Generated by Django 5.0.14 on 2026-04-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Quản trị viên"),
                    ("doctor", "Bác sĩ"),
                    ("nurse", "Điều dưỡng / Y tá"),
                    ("patient", "Bệnh nhân"),
                ],
                default="patient",
                max_length=10,
                verbose_name="Vai trò",
            ),
        ),
    ]
