# Generated by Django 5.0.14 on 2026-04-14 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Nam"), ("F", "Nữ")],
                        max_length=1,
                        verbose_name="Giới tính",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Địa chỉ")),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Chưa xác định"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="Nhóm máu",
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Chẩn đoán")),
                (
                    "admission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày nhập viện"
                    ),
                ),
                (
                    "discharge_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày xuất viện"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Người liên hệ khẩn cấp",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="SĐT khẩn cấp"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="doctors.doctorprofile",
                        verbose_name="Bác sĩ phụ trách",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tài khoản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ bệnh nhân",
                "verbose_name_plural": "Hồ sơ bệnh nhân",
            },
        ),
        migrations.CreateModel(
            name="LegRecoveryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(verbose_name="Thời gian ghi nhận"),
                ),
                (
                    "affected_leg",
                    models.CharField(
                        choices=[
                            ("left", "Chân trái"),
                            ("right", "Chân phải"),
                            ("both", "Cả hai chân"),
                        ],
                        max_length=5,
                        verbose_name="Chân bị ảnh hưởng",
                    ),
                ),
                (
                    "muscle_strength",
                    models.IntegerField(
                        choices=[
                            (0, "Độ 0 – Không có co cơ"),
                            (1, "Độ 1 – Co cơ nhẹ, không tạo chuyển động"),
                            (2, "Độ 2 – Vận động khi loại bỏ trọng lực"),
                            (3, "Độ 3 – Thắng được trọng lực"),
                            (4, "Độ 4 – Thắng được lực cản nhẹ"),
                            (5, "Độ 5 – Sức mạnh bình thường"),
                        ],
                        verbose_name="Sức mạnh cơ (MRC 0–5)",
                    ),
                ),
                (
                    "range_of_motion",
                    models.IntegerField(verbose_name="Biên độ vận động (độ)"),
                ),
                (
                    "pain_level",
                    models.IntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        verbose_name="Mức độ đau (VAS 0–10)",
                    ),
                ),
                (
                    "swelling_level",
                    models.IntegerField(
                        choices=[
                            (0, "Không sưng"),
                            (1, "Sưng nhẹ"),
                            (2, "Sưng vừa"),
                            (3, "Sưng nặng"),
                        ],
                        verbose_name="Mức độ sưng",
                    ),
                ),
                (
                    "walking_ability",
                    models.CharField(
                        choices=[
                            ("0", "Không thể đi lại"),
                            ("1", "Chỉ nằm/ngồi trên giường"),
                            ("2", "Xe lăn"),
                            ("3", "Khung đỡ (walker)"),
                            ("4", "Nạng (crutches)"),
                            ("5", "Gậy (cane)"),
                            ("6", "Đi độc lập"),
                        ],
                        max_length=2,
                        verbose_name="Khả năng đi lại",
                    ),
                ),
                (
                    "recovery_percentage",
                    models.IntegerField(default=0, verbose_name="Tỷ lệ phục hồi (%)"),
                ),
                (
                    "physical_therapy_notes",
                    models.TextField(
                        blank=True, verbose_name="Ghi chú vật lý trị liệu"
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(blank=True, verbose_name="Ghi chú bác sĩ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_recoveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người ghi nhận",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_records",
                        to="patients.patientprofile",
                        verbose_name="Bệnh nhân",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ phục hồi",
                "verbose_name_plural": "Hồ sơ phục hồi",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ECGRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(verbose_name="Thời gian đo")),
                (
                    "heart_rate",
                    models.PositiveIntegerField(verbose_name="Nhịp tim (bpm)"),
                ),
                ("pr_interval", models.FloatField(verbose_name="Khoảng PR (ms)")),
                ("qrs_duration", models.FloatField(verbose_name="Thời gian QRS (ms)")),
                ("qt_interval", models.FloatField(verbose_name="Khoảng QT (ms)")),
                (
                    "qtc_interval",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Khoảng QTc (ms)"
                    ),
                ),
                (
                    "rr_interval",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Khoảng RR (ms)"
                    ),
                ),
                (
                    "p_wave_amplitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Biên độ sóng P (mV)"
                    ),
                ),
                (
                    "qrs_amplitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Biên độ QRS (mV)"
                    ),
                ),
                (
                    "t_wave_amplitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Biên độ sóng T (mV)"
                    ),
                ),
                (
                    "st_change",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Thay đổi ST (mm)"
                    ),
                ),
                (
                    "rhythm",
                    models.CharField(
                        choices=[
                            ("normal_sinus", "Nhịp xoang bình thường"),
                            ("sinus_tach", "Nhịp nhanh xoang (>100 bpm)"),
                            ("sinus_brad", "Nhịp chậm xoang (<60 bpm)"),
                            ("afib", "Rung nhĩ (AF)"),
                            ("aflutter", "Cuồng nhĩ"),
                            ("vt", "Nhịp nhanh thất (VT)"),
                            ("vf", "Rung thất (VF)"),
                            ("first_deg_block", "Block nhĩ thất độ I"),
                            ("second_deg_block", "Block nhĩ thất độ II"),
                            ("third_deg_block", "Block nhĩ thất độ III"),
                            ("lbbb", "Block nhánh trái (LBBB)"),
                            ("rbbb", "Block nhánh phải (RBBB)"),
                            ("pvc", "Ngoại tâm thu thất (PVC)"),
                            ("pac", "Ngoại tâm thu nhĩ (PAC)"),
                            ("other", "Khác"),
                        ],
                        default="normal_sinus",
                        max_length=30,
                        verbose_name="Loại nhịp",
                    ),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, verbose_name="Có bất thường"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Nhận xét")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_ecgs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người thực hiện",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecg_records",
                        to="patients.patientprofile",
                        verbose_name="Bệnh nhân",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kết quả ECG",
                "verbose_name_plural": "Kết quả ECG",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
