# Generated by Django 5.0.14 on 2026-04-15 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="allergies",
            field=models.TextField(blank=True, verbose_name="Dị ứng"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="chief_complaint",
            field=models.TextField(
                blank=True, verbose_name="Lý do vào viện / Triệu chứng chính"
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="current_medications",
            field=models.TextField(blank=True, verbose_name="Thuốc đang dùng"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="family_history",
            field=models.TextField(blank=True, verbose_name="Tiền sử gia đình"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="past_medical_history",
            field=models.TextField(blank=True, verbose_name="Tiền sử bệnh lý"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="present_illness",
            field=models.TextField(blank=True, verbose_name="Bệnh sử hiện tại"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="social_history",
            field=models.TextField(blank=True, verbose_name="Tiền sử xã hội"),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="surgical_history",
            field=models.TextField(blank=True, verbose_name="Tiền sử phẫu thuật"),
        ),
        migrations.CreateModel(
            name="ExaminationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateTimeField(verbose_name="Ngày giờ khám")),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Huyết áp tâm thu (mmHg)"
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Huyết áp tâm trương (mmHg)"
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nhịp tim (bpm)"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nhịp thở (lần/phút)"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Nhiệt độ (°C)"
                    ),
                ),
                (
                    "spo2",
                    models.FloatField(blank=True, null=True, verbose_name="SpO₂ (%)"),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Cân nặng (kg)"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Chiều cao (cm)"
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, verbose_name="Lý do khám / Triệu chứng"
                    ),
                ),
                (
                    "clinical_findings",
                    models.TextField(
                        blank=True, verbose_name="Kết quả thăm khám lâm sàng"
                    ),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="Chẩn đoán")),
                (
                    "treatment_plan",
                    models.TextField(
                        blank=True, verbose_name="Hướng điều trị / Kế hoạch"
                    ),
                ),
                (
                    "prescription",
                    models.TextField(blank=True, verbose_name="Đơn thuốc"),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày tái khám"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú thêm")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "examined_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="examinations_done",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bác sĩ khám",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examination_records",
                        to="patients.patientprofile",
                        verbose_name="Bệnh nhân",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử khám",
                "verbose_name_plural": "Lịch sử khám",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="RehabilitationAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessed_at",
                    models.DateTimeField(verbose_name="Thời điểm đánh giá"),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("initial", "Đánh giá ban đầu"),
                            ("progress", "Đánh giá tiến trình"),
                            ("discharge", "Đánh giá xuất viện"),
                        ],
                        default="progress",
                        max_length=20,
                        verbose_name="Loại đánh giá",
                    ),
                ),
                (
                    "barthel_index",
                    models.IntegerField(
                        blank=True,
                        help_text="0=phụ thuộc hoàn toàn, 100=hoàn toàn độc lập",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Chỉ số Barthel (0–100)",
                    ),
                ),
                (
                    "fim_score",
                    models.IntegerField(
                        blank=True,
                        help_text="18=phụ thuộc hoàn toàn, 126=độc lập hoàn toàn",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(126),
                        ],
                        verbose_name="FIM – Đo lường độc lập chức năng (18–126)",
                    ),
                ),
                (
                    "mrs_score",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Độ 0"),
                            (1, "Độ 1"),
                            (2, "Độ 2"),
                            (3, "Độ 3"),
                            (4, "Độ 4"),
                            (5, "Độ 5"),
                            (6, "Độ 6"),
                        ],
                        help_text="0=không triệu chứng, 6=tử vong",
                        null=True,
                        verbose_name="Thang Rankin có sửa đổi – mRS (0–6)",
                    ),
                ),
                (
                    "fugl_meyer_upper",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(66),
                        ],
                        verbose_name="Fugl-Meyer chi trên (0–66)",
                    ),
                ),
                (
                    "fugl_meyer_lower",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(34),
                        ],
                        verbose_name="Fugl-Meyer chi dưới (0–34)",
                    ),
                ),
                (
                    "rivermead_motor_index",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(15),
                        ],
                        verbose_name="Chỉ số vận động Rivermead – RMI (0–15)",
                    ),
                ),
                (
                    "mas_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(48),
                        ],
                        verbose_name="Thang vận động MAS (0–48)",
                    ),
                ),
                (
                    "motricity_index_upper",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Chỉ số vận động chi trên (Motricity Index)",
                    ),
                ),
                (
                    "motricity_index_lower",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Chỉ số vận động chi dưới (Motricity Index)",
                    ),
                ),
                (
                    "rom_notes",
                    models.TextField(
                        blank=True,
                        verbose_name="Tầm vận động khớp – ROM (ghi chú góc khớp)",
                    ),
                ),
                (
                    "berg_balance_scale",
                    models.IntegerField(
                        blank=True,
                        help_text="< 45: nguy cơ ngã cao",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(56),
                        ],
                        verbose_name="Thang thăng bằng Berg (0–56)",
                    ),
                ),
                (
                    "dynamic_gait_index",
                    models.IntegerField(
                        blank=True,
                        help_text="< 19: nguy cơ ngã",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                        verbose_name="Chỉ số dáng đi động – DGI (0–24)",
                    ),
                ),
                (
                    "six_minute_walk",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Kiểm tra đi bộ 6 phút – 6MWT (mét)",
                    ),
                ),
                (
                    "pain_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Thang điểm đau (NRS 0–10)",
                    ),
                ),
                (
                    "dash_score",
                    models.FloatField(
                        blank=True,
                        help_text="0=không hạn chế, 100=hạn chế nặng",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Thang điểm DASH – chức năng chi trên (0–100)",
                    ),
                ),
                (
                    "nihss_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(42),
                        ],
                        verbose_name="Thang điểm NIHSS – lượng giá đột quỵ (0–42)",
                    ),
                ),
                (
                    "bp_systolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Huyết áp tâm thu (mmHg)"
                    ),
                ),
                (
                    "bp_diastolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Huyết áp tâm trương (mmHg)"
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nhịp tim (bpm)"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Nhịp thở (lần/phút)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Nhận xét tổng thể"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rehab_assessments_done",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người đánh giá",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rehab_assessments",
                        to="patients.patientprofile",
                        verbose_name="Bệnh nhân",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá phục hồi chức năng",
                "verbose_name_plural": "Đánh giá phục hồi chức năng",
                "ordering": ["-assessed_at"],
            },
        ),
    ]
