# Generated by Django 5.0.14 on 2026-04-15 09:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientprofile_allergies_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(verbose_name="Ngày giờ cấp thuốc")),
                ("diagnosis", models.TextField(blank=True, verbose_name="Chẩn đoán dùng cho đơn")),
                (
                    "clinical_notes",
                    models.TextField(blank=True, verbose_name="Tóm tắt lâm sàng / chỉ định"),
                ),
                ("medications", models.TextField(verbose_name="Thuốc được kê")),
                (
                    "dosage_instructions",
                    models.TextField(blank=True, verbose_name="Cách dùng / hướng dẫn dùng thuốc"),
                ),
                ("advice", models.TextField(blank=True, verbose_name="Dặn dò thêm")),
                (
                    "follow_up_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày tái khám"),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(blank=True, null=True, verbose_name="Huyết áp tâm thu (mmHg)"),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, null=True, verbose_name="Huyết áp tâm trương (mmHg)"),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="Nhịp tim (bpm)"),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="Nhịp thở (lần/phút)"),
                ),
                (
                    "temperature",
                    models.FloatField(blank=True, null=True, verbose_name="Nhiệt độ (°C)"),
                ),
                (
                    "spo2",
                    models.FloatField(blank=True, null=True, verbose_name="SpO₂ (%)"),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, null=True, verbose_name="Cân nặng (kg)"),
                ),
                (
                    "pain_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Mức độ đau (0–10)",
                    ),
                ),
                (
                    "blood_glucose",
                    models.FloatField(blank=True, null=True, verbose_name="Đường huyết mao mạch (mmol/L)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Ghi chú nội bộ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "examination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="patients.examinationrecord",
                        verbose_name="Lần khám liên quan",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="patients.patientprofile",
                        verbose_name="Bệnh nhân",
                    ),
                ),
                (
                    "prescribed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bác sĩ chỉ định",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phiếu chỉ định thuốc",
                "verbose_name_plural": "Phiếu chỉ định thuốc",
                "ordering": ["-issued_at"],
            },
        ),
    ]