# Generated by Django 5.0.14 on 2026-04-15 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_prescriptionrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="cadence",
            field=models.FloatField(blank=True, null=True, verbose_name="Cadence (bước/phút)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="fatigue_index",
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name="Mức mệt (fatigue index 0–10)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="gait_speed",
            field=models.FloatField(blank=True, null=True, verbose_name="Tốc độ dáng đi (m/s)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="heart_rate",
            field=models.IntegerField(blank=True, null=True, verbose_name="Nhịp tim (HR, bpm)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="imu_acceleration",
            field=models.FloatField(blank=True, null=True, verbose_name="IMU acceleration (m/s²)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="imu_velocity",
            field=models.FloatField(blank=True, null=True, verbose_name="IMU velocity (m/s)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="plantar_force",
            field=models.FloatField(blank=True, null=True, verbose_name="Lực đạp chân / plantar force (N)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="spo2",
            field=models.FloatField(blank=True, null=True, verbose_name="SpO₂ (%)"),
        ),
        migrations.AddField(
            model_name="legrecoveryrecord",
            name="step_length",
            field=models.FloatField(blank=True, null=True, verbose_name="Chiều dài bước (cm)"),
        ),
    ]