# Generated by Django 5.0.14 on 2026-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_legrecoveryrecord_extended_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="discharge_condition",
            field=models.CharField(blank=True, choices=[('', 'Chưa áp dụng'), ('recovered', 'Khỏi / hồi phục tốt'), ('improved', 'Đỡ / cải thiện'), ('stable', 'Ổn định'), ('transferred', 'Chuyển viện'), ('ama', 'Xin về / trái chỉ định'), ('other', 'Khác')], default='', max_length=20, verbose_name='Tình trạng xuất viện'),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="treatment_status",
            field=models.CharField(choices=[('inpatient', 'Điều trị nội viện'), ('home', 'Điều trị tại nhà'), ('discharged', 'Đã xuất viện')], default='inpatient', max_length=20, verbose_name='Trạng thái điều trị'),
        ),
    ]