# Generated by Django 5.0.14 on 2026-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patientprofile_treatment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="postoperative_status",
            field=models.CharField(blank=True, choices=[('', 'Chưa áp dụng'), ('stable', 'Hậu phẫu ổn định'), ('monitoring', 'Đang theo dõi sát'), ('improving', 'Đang cải thiện'), ('complication', 'Có biến chứng'), ('critical', 'Nặng / cần can thiệp thêm'), ('recovered', 'Phục hồi tốt sau mổ')], default='', max_length=20, verbose_name='Tình trạng hậu phẫu'),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="surgery_date",
            field=models.DateField(blank=True, null=True, verbose_name='Ngày phẫu thuật'),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="surgery_name",
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên phẫu thuật / thủ thuật'),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="surgery_status",
            field=models.CharField(choices=[('none', 'Chưa có chỉ định phẫu thuật'), ('indicated', 'Có chỉ định phẫu thuật'), ('planned', 'Đã lên kế hoạch phẫu thuật'), ('pre_op', 'Đang chuẩn bị tiền phẫu'), ('post_op', 'Đang hậu phẫu'), ('completed', 'Đã phẫu thuật'), ('cancelled', 'Hoãn / hủy phẫu thuật')], default='none', max_length=20, verbose_name='Trạng thái phẫu thuật'),
        ),
    ]