# Generated by Django 5.0.14 on 2026-04-14 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="Chuyên khoa"),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Số chứng chỉ hành nghề",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("cardiology", "Tim mạch"),
                            ("rehabilitation", "Phục hồi chức năng"),
                            ("orthopedics", "Chỉnh hình - Chấn thương"),
                            ("neurology", "Thần kinh"),
                            ("internal", "Nội tổng quát"),
                            ("surgery", "Ngoại tổng quát"),
                            ("other", "Khác"),
                        ],
                        default="rehabilitation",
                        max_length=20,
                        verbose_name="Khoa",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số năm kinh nghiệm"
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Giới thiệu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tài khoản",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hồ sơ bác sĩ",
                "verbose_name_plural": "Hồ sơ bác sĩ",
            },
        ),
    ]
